--------------------------------------------------------
--  已建立檔案 - 星期四-八月-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FACILITY
--------------------------------------------------------

  CREATE TABLE "STUDENT"."FACILITY" 
   (	"FACILITY_NO" VARCHAR2(20 BYTE), 
	"FC_TYPE" NVARCHAR2(20), 
	"VILLAGE_NO" NVARCHAR2(20), 
	"ADDRESS" NVARCHAR2(20), 
	"PPL_AMOUNT" NUMBER(*,0), 
	"POLICE_NO" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into STUDENT.FACILITY
SET DEFINE OFF;
Insert into STUDENT.FACILITY (FACILITY_NO,FC_TYPE,VILLAGE_NO,ADDRESS,PPL_AMOUNT,POLICE_NO) values ('F02','大樓','C002','苗栗縣竹南鎮和平街79號',5000,'M001');
Insert into STUDENT.FACILITY (FACILITY_NO,FC_TYPE,VILLAGE_NO,ADDRESS,PPL_AMOUNT,POLICE_NO) values ('F03','大樓','C003','苗栗縣竹南鎮龍山路三段142號',1072,'M001');
Insert into STUDENT.FACILITY (FACILITY_NO,FC_TYPE,VILLAGE_NO,ADDRESS,PPL_AMOUNT,POLICE_NO) values ('F07','大樓','C005','苗栗縣苗栗市博愛街109號',2038,'M002');
--------------------------------------------------------
--  DDL for Index SYS_C008355
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."SYS_C008355" ON "STUDENT"."FACILITY" ("FACILITY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FACILITY
--------------------------------------------------------

  ALTER TABLE "STUDENT"."FACILITY" ADD PRIMARY KEY ("FACILITY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
