--------------------------------------------------------
--  已建立檔案 - 星期四-八月-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POLICE
--------------------------------------------------------

  CREATE TABLE "STUDENT"."POLICE" 
   (	"POLICE_NO" VARCHAR2(20 BYTE), 
	"POLICE_NAME" NVARCHAR2(20), 
	"POLICE_ADDRESS" NVARCHAR2(20), 
	"POLICE_TEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into STUDENT.POLICE
SET DEFINE OFF;
Insert into STUDENT.POLICE (POLICE_NO,POLICE_NAME,POLICE_ADDRESS,POLICE_TEL) values ('M001','竹南分局','苗栗縣竹南鎮民族街72號','03 747 4796');
Insert into STUDENT.POLICE (POLICE_NO,POLICE_NAME,POLICE_ADDRESS,POLICE_TEL) values ('M002','苗栗分局','苗栗縣苗栗市金鳳街109號','03 732 0059');
Insert into STUDENT.POLICE (POLICE_NO,POLICE_NAME,POLICE_ADDRESS,POLICE_TEL) values ('M003','頭份分局','苗栗縣頭份市中興路503號','03 766 3004');
--------------------------------------------------------
--  DDL for Index POLICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."POLICE_PK" ON "STUDENT"."POLICE" ("POLICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table POLICE
--------------------------------------------------------

  ALTER TABLE "STUDENT"."POLICE" MODIFY ("POLICE_NO" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."POLICE" ADD CONSTRAINT "POLICE_PK" PRIMARY KEY ("POLICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
