--------------------------------------------------------
--  已建立檔案 - 星期四-八月-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VILLAGE
--------------------------------------------------------

  CREATE TABLE "STUDENT"."VILLAGE" 
   (	"VIL_NO" VARCHAR2(20 BYTE), 
	"VIL_NAME" NVARCHAR2(20), 
	"VIL_OFFICE" NVARCHAR2(20), 
	"VIL_TEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into STUDENT.VILLAGE
SET DEFINE OFF;
Insert into STUDENT.VILLAGE (VIL_NO,VIL_NAME,VIL_OFFICE,VIL_TEL) values ('C001','大埔里','竹南鎮公義路1035號','03 758 1072');
Insert into STUDENT.VILLAGE (VIL_NO,VIL_NAME,VIL_OFFICE,VIL_TEL) values ('C002','竹南里','竹南鎮竹南里中山路 103 號','037-472735');
Insert into STUDENT.VILLAGE (VIL_NO,VIL_NAME,VIL_OFFICE,VIL_TEL) values ('C003','山佳里','竹南鎮山佳里國光街 14 號','037-614186');
Insert into STUDENT.VILLAGE (VIL_NO,VIL_NAME,VIL_OFFICE,VIL_TEL) values ('C004','埔頂里','後龍鎮埔頂里中興路136-1號','037-724839');
Insert into STUDENT.VILLAGE (VIL_NO,VIL_NAME,VIL_OFFICE,VIL_TEL) values ('C005','綠苗里','苗栗市綠苗里中正路 766 號','037-333240');
Insert into STUDENT.VILLAGE (VIL_NO,VIL_NAME,VIL_OFFICE,VIL_TEL) values ('C006','民族里','民族里民族路96號','037-660001');
Insert into STUDENT.VILLAGE (VIL_NO,VIL_NAME,VIL_OFFICE,VIL_TEL) values ('C007','忠孝里','忠孝里光大街82號','037-661145');
Insert into STUDENT.VILLAGE (VIL_NO,VIL_NAME,VIL_OFFICE,VIL_TEL) values ('C008','信義里','信義里信義路53巷1號','037-616072');
--------------------------------------------------------
--  DDL for Index VILLAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."VILLAGE_PK" ON "STUDENT"."VILLAGE" ("VIL_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VILLAGE
--------------------------------------------------------

  ALTER TABLE "STUDENT"."VILLAGE" MODIFY ("VIL_NO" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."VILLAGE" ADD CONSTRAINT "VILLAGE_PK" PRIMARY KEY ("VIL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
